name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn --ignore-engines install

      - name: Run test and generate coverage report
        run: yarn test --coverage --watchAll=false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Copy Cypress.json
        run: cp cypress.json.example cypress.json
        
      - name: path
        run: ls
  
      - name: Cypress run
        run: yarn cy:run

